package com.csumb.cst363;

import java.math.BigDecimal;

/*
 * This class is used to transfer data to/from prescription template pages.
 */
public class Prescription {
	
	private Integer RX;  // primary key generated by database.

	// following fields are set when doctor creates a prescription.
	private Integer drugID;
	private String drugName;
	private Integer qty;
	private String patientSSN;
	private String patientFName;
	private String patientLName;
	private String doctorSSN;
	private String doctorFName;
	private String doctorLName;
	private String datePrescribed;
	// following fields will be null or blank until prescription has been filled.
	private Integer pharmacyID;
	private String pharmacyStreet;
	private String pharmacyCity;
	private String pharmacyState;
	private String pharmacyZip;
	private String pharmacyPhone;
	private String pharmacyName;
	private String dateFilled;    
	private BigDecimal cost;

	public Integer getRX() {
		return RX;
	}

	public void setRX(Integer RX) {
		this.RX = RX;
	}

	public Integer getDrugID() {
		return drugID;
	}

	public void setDrugID(Integer drugID) {
		this.drugID = drugID;
	}

	public String getDrugName() {
		return drugName;
	}

	public void setDrugName(String drugName) {
		this.drugName = drugName;
	}

	public Integer getQty() {
		return qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	public String getPatientSSN() {
		return patientSSN;
	}

	public void setPatientSSN(String patientSSN) {
		this.patientSSN = patientSSN;
	}

	public String getPatientFName() {
		return patientFName;
	}

	public void setPatientFName(String patientFName) {
		this.patientFName = patientFName;
	}

	public String getPatientLName() {
		return patientLName;
	}

	public void setPatientLName(String patientLName) {
		this.patientLName = patientLName;
	}

	public String getDoctorSSN() {
		return doctorSSN;
	}

	public void setDoctorSSN(String doctorSSN) {
		this.doctorSSN = doctorSSN;
	}

	public String getDoctorFName() {
		return doctorFName;
	}

	public void setDoctorFName(String doctorFName) {
		this.doctorFName = doctorFName;
	}

	public String getDoctorLName() {
		return doctorLName;
	}

	public void setDoctorLName(String doctorLName) {
		this.doctorLName = doctorLName;
	}

	public String getDatePrescribed() {
		return datePrescribed;
	}

	public void setDatePrescribed(String datePrescribed) {
		this.datePrescribed = datePrescribed;
	}

	public Integer getPharmacyID() {
		return pharmacyID;
	}

	public void setPharmacyID(Integer pharmacyID) {
		this.pharmacyID = pharmacyID;
	}

	public String getPharmacyStreet() {
		return pharmacyStreet;
	}

	public void setPharmacyStreet(String pharmacyStreet) {
		this.pharmacyStreet = pharmacyStreet;
	}

	public String getPharmacyCity() {
		return pharmacyCity;
	}

	public void setPharmacyCity(String pharmacyCity) {
		this.pharmacyCity = pharmacyCity;
	}

	public String getPharmacyState() {
		return pharmacyState;
	}

	public void setPharmacyState(String pharmacyState) {
		this.pharmacyState = pharmacyState;
	}

	public String getPharmacyZip() {
		return pharmacyZip;
	}

	public void setPharmacyZip(String pharmacyZip) {
		this.pharmacyZip = pharmacyZip;
	}

	public String getPharmacyPhone() {
		return pharmacyPhone;
	}

	public void setPharmacyPhone(String pharmacyPhone) {
		this.pharmacyPhone = pharmacyPhone;
	}

	public String getPharmacyName() {
		return pharmacyName;
	}

	public void setPharmacyName(String pharmacyName) {
		this.pharmacyName = pharmacyName;
	}

	public String getDateFilled() {
		return dateFilled;
	}

	public void setDateFilled(String dateFilled) {
		this.dateFilled = dateFilled;
	}

	public BigDecimal getCost() {
		return cost;
	}

	public void setCost(BigDecimal cost) {
		this.cost = cost;
	}

	@Override
	public String toString() {
		return "Prescription{" +
			"RX=" + RX +
			", drugID=" + drugID +
			", drugName='" + drugName + '\'' +
			", qty=" + qty +
			", patientSSN='" + patientSSN + '\'' +
			", patientFName='" + patientFName + '\'' +
			", patientLName='" + patientLName + '\'' +
			", doctorSSN='" + doctorSSN + '\'' +
			", doctorFName='" + doctorFName + '\'' +
			", doctorLName='" + doctorLName + '\'' +
			", datePrescribed='" + datePrescribed + '\'' +
			", pharmacyID=" + pharmacyID +
			", pharmacyStreet='" + pharmacyStreet + '\'' +
			", pharmacyCity='" + pharmacyCity + '\'' +
			", pharmacyState='" + pharmacyState + '\'' +
			", pharmacyZip='" + pharmacyZip + '\'' +
			", pharmacyPhone='" + pharmacyPhone + '\'' +
			", pharmacyName='" + pharmacyName + '\'' +
			", dateFilled='" + dateFilled + '\'' +
			", cost='" + cost + '\'' +
			'}';
	}
}
